source 'https://rubygems.org'
ruby '2.5.1'
gem 'rspec'
gem 'twitter'
gem 'pry'
gem 'rubocop', '~> 0.57.2'
gem 'dotenv'
gem 'nokogiri'
gem 'launchy'
gem 'json'
gem 'google_drive'
gem 'csv'
gem 'sinatra'
gem 'shotgun'
